version: '3'
services:
  node:
    build: .
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=8080
    networks:
      - vsosevich-net
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
  postgres:
    build: ./database
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - vsosevich-net
    volumes:
      - ./database:/user/app/database

networks:
  vsosevich-net:
    driver: bridge
