version: '3'
services:
  node:
    build: .
    container_name: 'node'
    image: 'volodymyrsosevich/rs-school-node'
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=postgres
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - vsosevich-net
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
      - /user/app/node_modules
  postgres:
    build: ./database
    container_name: 'postgres'
    image: 'volodymyrsosevich/rs-school-postgres'
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGDATA: ${POSTGRES_DATA}
    networks:
      - vsosevich-net
    volumes:
      - ./database:/var/lib/postgresql/data

networks:
  vsosevich-net:
    driver: bridge
